<html>
<head>
<title>EPIC - CDB MapServer </title>
<style type="text/css">
<!--
body {  font-family: Arial, Helvetica, sans-serif; font-size: 12px} -->
</style>
</head>
<body bgcolor="#FFFFFF" text="#000000" link="#0000FF">
<h1>EPIC- CDB MapServer - version 1.0.0</h1>
A Product of: <a href="https://www.vatcinc.com" target="_blank"><img src="images/EPIC_Ready.png" border="0" alt="Developed by Visual Awarness Technologies and Consulting Inc"/></a>
<h2>Introduction</h2>
<p>Welcome to EPIC Builder v1.0.0, CDB MapServices for Windows, developed by
developed by <a href="https://www.vatcinc.com" target="_blank">Visual Awarness Technologies and Consulting Inc</a> <a href="https://www.epicready.com" target="_blank">EPIC Ready</a>.
</p>
<p>EPIC CDB Test Map:</p>
<h2>CDB Test Map</h2>
<iframe name="CDB test map" width="1280" height="1024" frameborder="0" scrolling="no" src="/cgi-bin/mapserv.exe?map=C:/Program Files/Visual Awareness Technologies and Consulting Inc/apps/cdb-demo/cdb.map&MODE=browse&TEMPLATE=openlayers&LAYERS=all"></iframe>
  <li>mapfile at <i>C:/Program Files/Visual Awareness Technologies and Consulting Inc/apps/cdb-demo/cdb.map</i></li>
  <li>open map viewer in new <a href="/cgi-bin/mapserv.exe?map=C:/Program Files/Visual Awareness Technologies and Consulting Inc/apps/cdb-demo/cdb.map&MODE=browse&TEMPLATE=openlayers&LAYERS=all" target="_blank">window</a></li>
</body>
</html>
