MESSAGE("Specialized FindNGHTTP2 Called")
if( NOT $ENV{NGHTTP2_LIBRARY} STREQUAL "" )
  SET(NGHTTP2_LIBRARY $ENV{NGHTTP2_LIBRARY})


  set(NGHTTP2_LIBRARIES ${NGHTTP2_LIBRARY})

  if( NOT $ENV{NGHTTP2_INCLUDE_DIR} STREQUAL "" )
     SET(NGHTTP2_INCLUDE_DIR $ENV{NGHTTP2_INCLUDE_DIR})
  endif()


  mark_as_advanced(NGHTTP2_LIBRARY NGHTTP2_INCLUDE_DIR)

  SET(NGHTTP2_FOUND TRUE)

  MESSAGE("FindNGHTTP2 Set By Envionment")


endif()